name: Nightly Release

on:
  schedule:
    # Runs at midnight UTC
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add Remote Repository
        run: |
          git remote add upstream https://github.com/nicklockwood/SwiftFormat.git
          git remote -v

      - name: Fetch from Upstream
        run: |
          git fetch upstream

      - name: Hard Reset to Upstream
        run: |
          git reset --hard upstream/develop
          
      - name: Force Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: develop
          force: true

  create-release:
    needs: sync-develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          persist-credentials: false
          
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      - name: Generate Tag Name
        id: tag
        run: |
          echo "TAG_NAME=SwiftFormat-nightly-$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          
      - name: Create Tag
        run: |
          git tag ${{ env.TAG_NAME }}
          
      - name: Push Tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: refs/tags/${{ env.TAG_NAME }}
          force: true
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          body: |
            Nightly build of the SwiftFormat `develop` branch on $(date +'%B %-d, %Y').
            
            Nightly builds are subject to breaking changes.

            Source code is available at https://github.com/${{ github.repository }}/tree/${{ env.TAG_NAME }}
          draft: false
          prerelease: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}